<div id="texto">
	<h1>Antecedentes</h1>
	<p>El 11 de Septiembre de 1933 llego la primera Misión Salesiana a Puerto Ayacucho, Territorio Amazonas. El Gobernador de entonces, Coronel Jesús Canelón G., junto a toda la población (que apenas alcanzaban unos 200 habitantes) recibió a la misión salesiana presidida por Monseñor Enrique De Ferrari. Al respecto Iribertegui y Martín (1994) señalan:</p>
	<p>…Vino el Sr. Gobernador…con los otros empleados a saludar a Monseñor, y lo llevo a tomar posesión de su palacio: una choza con tres piezas y un locutorio, con techo sin paredes. Monseñor acomodó por el momento las cosas…y mandó construir cuatro casas enfrente de su “palacio”… El Padre Burk narra que se encontraban a unos cincuenta pasos del puerto-embarcadero (hoy muelle de Puerto Ayacucho). Allí comenzó a funcionar el Dispensario Médico de la Misión.</p>
	<p>…Constituyó una auténtica providencia no solo para los habitantes de Puerto Ayacucho, sino para todo el Territorio. Para curarse y pedir medicinas llegaban gentes de San Fernando de Atabapo y de otras poblaciones distantes, e incluso de Puerto Carreño y algunos pueblos colombianos. Comenzó a funcionar atendido por el Padre Burk el mismo día de la llegada de la primera expedición a Puerto Ayacucho. Aquella noche pudieron salvar gracias a las medicinas de la enfermería, a un pobre hombre que había sido mordido por una serpiente venenosa. El dispensario socorrió y benefició a muchísimas personas… Paciencia y constancia fueron necesarias para ir urbanizando el poblado, elevando el nivel de profilaxis individual y social, para que Puerto Ayacucho se pareciera a cualquier ciudad del resto de la nación.</p>
	<p>El primer médico en llegar a Puerto Ayacucho lo hizo el 27 de Octubre de 1933, a través de la Misión Salesiana. Con el transcurrir del tiempo, hacia 1935 la Misión se muda a una nueva sede, ubicada detrás del actual Hotel Tobogán de la Avenida Orinoco (Frente al Colegio Madre Mazzarello). Allí se continúo la labor de dispensario médico con el Padre Burk.</p>
	<p>Iribertegui (2000) señala lo siguiente en relación a la fundación del hospital:</p>
	<p>La primera Medica tura funcionó en la actual calle Atabapo, en la casa del Dr. López Rivas. La bendición de este Hospital “Simón Bolívar” al que se refiere la crónica salesiana, al parecer, es la actual Casa Sindical (Calle Atabapo) que por ser una construcción tan grande para la población de entonces, con gran dificultad podía ser dotada medianamente, por lo que se optó por un Hospital más pequeño que estaba en la lomita del actual Barrio Táchira, un poco más arriba de la actual escuela. A ese Hospital, el Dr. Renato Planas, sucesor del Dr. López Rivas ya expulsado, le dio el nombre de “Dr. Plácido Daniel Rodríguez Rivero¨. Este nombre se mantiene durante el servicio médico del Dr. Agüero. Será el Dr. Ramón Kisley quien lo manda a borrar y le pone el nombre de ¨Dr. José Gregorio Hernández. La fecha exacta de este cambio no se precisa; sin embargo por las crónicas de la misión salesiana, se establece el lapso de Julio a Diciembre de 1946.</p>
	<p>Durante el gobierno del General Marcos Pérez Jiménez se inició la construcción del actual Hospital. El 19 de Marzo de 1957 se inauguró en Centro de Salud de Puerto Ayacucho, hoy Hospital “““Dr. José Gregorio Hernández”. (Llambí et al, 2002)</p>
	<p>El número de camas ha experimentado un aumento progresivo debido al incremento lento pero sostenido que ha cursado la población amazonense. Para ajustarse a esta realidad, igualmente ha sido inevitable el incremento del personal que labora en la institución y la ampliación de la infraestructura original, este ultimo proceso, no siempre conciliado con una efectiva planificación, ni en concordancia con las especificaciones técnicas definidas para instalaciones hospitalarias.</p>
	<p>El tiempo de vida del hospital y los aspectos resaltados en el párrafo precedente se conjugan para que en la actualidad las instalaciones del único hospital del Estado Amazonas confronte serios problemas: sistema eléctrico deficiente que atenta contra la operatividad de equipos, problemas de filtración en diferentes áreas que hacen imperante la necesidad de la impermeabilización del techo, red de aguas blancas y negras seriamente afectadas y daños estructurales graves. Así, se han ido creando y consolidando condiciones adversas tanto para el usuario que acude solicitando atención, como para el personal que aquí labora.</p>
	<p>Ha existido la voluntad de gobernantes para darle un nuevo Hospital al Estado Amazonas, sin embargo, este sueño aunque ya esté en marcha, aun es lejano. Es por ello que es necesario mejorar la prestación de los servicios en las instalaciones actualmente existentes.</p>
	<p>A pesar del comprometido escenario descrito, en la actualidad el problema capital de la institución se puede definir como “humano”; y se emplea el término para poder abarcar aspectos inherentes a las personas, tan variados como: valores, principios, motivación, mística, ética, capacidad y actitud, entre otros, pero donde también es ineludible tomar en cuenta lo referente a la deficiencia de personal, situación que atenta contra una oferta asistencial eficiente a la población.</p>
	<p>Es importante acotar que estos problemas se extienden a prácticamente todas las esferas laborales, no obstante, se considera que la situación del cuerpo medico es particularmente preocupante.</p>
</div>